### ISSUE TITLE
error in readme code

### ISSUE THREAD

**Issue by kosich** [tehwalris/socket-io-mocks#1]
Hi. Seem like following code from README fails:
`let io = new Server()`

It needs two calls, like
`let io = new Server()()`

Due to Server constructor returning stub:
https://github.com/tehwalris/socket-io-mocks/blob/master/src/server.js#L26-L29

P.S. thanks for this mock module, it came in handy!

**Comment by tehwalris** [comment]
Fixed in eda5def6 (0.1.5 on npm). I'm glad the mocks were useful :smile:
